### ISSUE TITLE
`java.io.IOException` when checkpointing inside Ubuntu/arm64 container on Ubuntu 24.04/amd64 host

### ISSUE THREAD

**Issue by TimPushkin** [TimPushkin/portable-crac-demo#1]
After updating to Ubuntu 24.04 I get the following error when trying to make a checkpoint inside Ubuntu/arm64 container on my amd64 host:
```
2024-06-04 12:22:33.968:INFO:ce.App:qtp712025048-27: Handling target: /checkpoint
2024-06-04 12:22:33.969:INFO:ce.App:main: Initiating checkpoint
Jun 04, 2024 12:22:34 PM jdk.internal.crac.LoggerContainer info
INFO: Starting checkpoint
2024-06-04 12:22:34.037:WARN:oejs.AbstractConnector:main: 
java.io.IOException: Invalid argument
	at java.base/sun.nio.ch.NativeThread.signal0(Native Method)
	at java.base/sun.nio.ch.NativeThread.signal(NativeThread.java:76)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.implCloseBlockingMode(ServerSocketChannelImpl.java:614)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.implCloseSelectableChannel(ServerSocketChannelImpl.java:649)
	at java.base/java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:258)
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:113)
	at org.eclipse.jetty.server.ServerConnector.close(ServerConnector.java:371)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStop(AbstractNetworkConnector.java:87)
	at org.eclipse.jetty.server.ServerConnector.doStop(ServerConnector.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	at org.eclipse.jetty.util.component.LifeCycle.stop(LifeCycle.java:164)
	at com.example.ServerManager.lambda$beforeCheckpoint$0(App.java:41)
	at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4266)
	at com.example.ServerManager.beforeCheckpoint(App.java:41)
	at org.crac.Core$ResourceWrapper.beforeCheckpoint(Core.java:88)
	at org.crac.Core$ResourceWrapper.invoke(Core.java:68)
	at jdk.proxy2/jdk.proxy2.$Proxy1.beforeCheckpoint(Unknown Source)
	at java.base/javax.crac.ResourceWrapper.beforeCheckpoint(ResourceWrapper.java:61)
	at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
	at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
	at java.base/javax.crac.ContextWrapper.beforeCheckpoint(ContextWrapper.java:47)
	at java.base/javax.crac.ResourceWrapper.beforeCheckpoint(ResourceWrapper.java:61)
	at java.base/jdk.crac.impl.AbstractContext.invokeBeforeCheckpoint(AbstractContext.java:44)
	at java.base/jdk.crac.impl.AbstractContext.beforeCheckpoint(AbstractContext.java:59)
	at java.base/jdk.crac.Core.checkpointRestore1(Core.java:158)
	at java.base/jdk.crac.Core.checkpointRestore(Core.java:299)
	at java.base/jdk.crac.Core.checkpointRestore(Core.java:278)
	at java.base/javax.crac.Core.checkpointRestore(Core.java:73)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.crac.Core$Compat.checkpointRestore(Core.java:141)
	at org.crac.Core.checkpointRestore(Core.java:237)
	at com.example.App.main(App.java:107)
2024-06-04 12:23:04.060:INFO:oejs.AbstractConnector:main: Stopped ServerConnector@6166e06f{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
<the rest of the output is cut off>
```

**Comment by TimPushkin** [comment]
The issue turned out be related to Docker and not to the JVM. Managed to fix it as described here: https://github.com/docker/buildx/issues/314#issuecomment-2016366785.
